services:
  discord-bot:
    container_name: pickem-command
    build: .
    restart: always
    env_file: .env
    ports:
      - '3000:3000' # Optional, only needed if your bot exposes a port
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
